#!/bin/bash
ngoyVersion=1.0.0-rc0
ngoyPath=build/tmp/ngoy-$ngoyVersion

if [ ! -e $ngoyPath ]; then
	echo "Extracting ngoy binaries..."
    gradle extractNgoy
fi
java -cp "$ngoyPath/*" ngoy.Ngoy $@
